version: 2.0
jobs:
  build:
    working_directory: ~/poi-router
    docker:
      - image: node:8.11.3
    steps:
      - checkout
      - run: npm install -g coffee-script grunt-cli
      - run: npm install
      - run: grunt build
      - run: npm test
