version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - node12
jobs:
  node12:
    working_directory: ~/poi-router
    docker:
      - image: node:12.8.1
    steps:
      - checkout
      - run: npm install -g coffee-script grunt-cli
      - run: npm install
      - run: grunt build
      - run: npm test
